### ISSUE TITLE
Add basic assertions section to docs

### ISSUE THREAD

**Issue by JVimes** [xbehave/xbehave.net#165]
For those of us who are new to xBehave and xUnit, it would be nice to have a section in the docs showing the recommended syntax for some common assertions, including expected exception assertions. If the fluent assertions library is the recommended approach, that's a good spot to mention it with a link. Much thanks.

**Comment by adamralph** [comment]
:+1: good idea. I'm on hols right now but feel free to make a start in the
meantime :wink:

**Comment by JVimes** [comment]
I'll do that. :) Only answers I need first are:
- Is there a pure xUnit expected-exception syntax that works in xBehave? `Assert.Throws<>(...)` seems to force my When and Then code into the same step. I'll include the fluent way (as demonstrated [here](https://gist.github.com/adamralph/5535794)) and a pure xUnit way if there's one that's not bad.
- Are there any other odd-ball assertions you can think of?

**Comment by adamralph** [comment]
Great!
- Record.Exception is pure xunit, so you can use that in a When and then
  use any of the standard xunit assertions in subsequent Then and Ands.
- Nothing else springs to mind right now

Thanks!

**Comment by JVimes** [comment]
Alright, I added it to the [documentation](https://github.com/xbehave/xbehave.net/wiki/Documentation), including the sidebar. I included the info from the FAQ about Fluent Assertions. Enjoy your vacation :)

**Comment by adamralph** [comment]
Looks good. Thanks very much!

**Comment by adamralph** [comment]
@JVimes thanks very much for creating that page. I just made some edits to make the scenario names more 'scenerio' rather than 'fact' and also aligned the xUnit.net and FluentAssertions example so that they only differ by the assertions.
