### ISSUE TITLE
Support ASP.NET 5 (vNext)

### ISSUE THREAD

**Issue by giggio** [xbehave/xbehave.net#214]
We have tried to use xbehave with ASPNET vNext as detailed by [the ASPNET team on Github](https://github.com/aspnet/Testing/wiki/How-to-create-test-projects) and we get some errors, probably the way xUnit is being dependent upon, but I am not sure.
We would like to be able to run xbehave along the new ASPNET version. I think that the ideal experience would be simple install a nuget and it works.

**Comment by giggio** [comment]
BTW, the current infrastructure seems to be using xUnit 2.

**Comment by adamralph** [comment]
Hi @giggio. This is currently being worked on as part of the conversion to xunit 2, see #51. The current beta release of 2.0 does not yet support vNext (see the checklist) but this will come in one of the next beta releases. The idea is for 2.0 to support all the same platforms that are supported by xunit 2.0 which includes vNext. As you describe,  the experience will be seamless, I.e. just install xbehave in exactly the same way as you install xunit and everything will Just Work :wink:

**Comment by adamralph** [comment]
Closing as this is part of #51

**Comment by giggio** [comment]
Sorry, @adamralph, I hadn't notice that it was on that list.

**Comment by adamralph** [comment]
np - watch out for a new beta soon. I think I'll do the vnext targets next.
