### ISSUE TITLE
Optional omission of arguments from scenario names in test output

### ISSUE THREAD

**Issue by adamralph** [xbehave/xbehave.net#37]
Proposed by @jamesfoster.

The example values should normally be included in the step descriptions, e.g.

``` C#
[Scenario]
[Example("Dr. Bill")]
[Example("Dr. Bob")]
public static void UserPostsToHisOwnBlog(string userName)
{
    "Given I am logged in as {0}"
        .Given(() => Site.Login(userName, "oranges"));
```

However, some people may choose not to do this and rely on the test output to show example values so we should default to preserving this behaviour.

The new optional feature can be enabled by applying

``` C#
[OmitArgumentsFromScenarioNames(true)]
```

at the method (scenario), class (feature) or assembly (product) level.

**Comment by adamralph** [comment]
@jamesfoster I've added the attribute we discussed to control this feature (see updated issue description)

Another reason for having this switched off by default is that if you have a step failure in VS using TD.NET or any other runner which only shows failures in the output, all you get is the name of the test that failed in the output window. This means that if say, a When or Then fails, even if your Given step shows the example value in it's text using "Given foo is {0}", you can't see this in the output window so you have no idea which example failed.

I guess if you are using another test runner which shows all the tests in a GUI next to each other this may be mitigated. I use TD.NET and for this reason I probably won't use this feature, but it's there for you to optionally switch on if you want it :wink:.

Something that is on the radar for either version 1.0 or 2.0 is to thoroughly re-work the test output towards something like that which is produced from Cucumber, i.e. features, scenarios and examples as first class citizens instead of being shoe-horned in to xUnit's test class and test method schema. When that happens this is bound to be revisited.

I'l push out a new beta shortly.

**Comment by jamesfoster** [comment]
Excellent.

This will definitely help eliminate my horizontal scrollbar ;)

**Comment by adamralph** [comment]
Latest changes pushed out as beta https://nuget.org/packages/Xbehave/0.15.0-beta04
