### ISSUE TITLE
Create a VS extension for pasting Gherkin into C#

### ISSUE THREAD

**Issue by adamralph** [xbehave/xbehave.net#49]
_This issue has been moved to https://github.com/xbehave/xbehave.net-visual-studio/issues/3_

I go to my user story in my issue tracker. I copy the Gherkin scenarios. I go to VS. I right click my code file. I click 'Paste Gherkin as C#'. My scenarios are pasted into the code file as C#. I feel good.

E.g.

``` Gherkin
Scenario: Dr. Bill posts to his own blog
  Given I am logged in as Dr. Bill
   When I try to post to "Expensive Therapy"
   Then I should see "Your article was published."
```

is converted to

``` C#
[Scenario]
public static void DrBillPostsToHisOwnBlog()
{
    "Given I am logged in as Dr. Bill"
        .Given(() => { });

    "When I try to post to \"Expensive Therapy\""
        .When(() => { });

    "Then I should see \"Your article was published.\""
        .Then(() => { });
}
```

**Comment by GraemeBradbury** [comment]
How do you want to integrate this with the xBehave.Net project?

I've got an initial naive implementation working at https://github.com/GraemeBradbury/xBehave-Paster

**Comment by adamralph** [comment]
Wow, this is awesome work!

Given that it's standalone and involves the VS API's, I think it makes
sense to stay as a separate solution in a new repo under the xbehave org.
Is that what you had in mind? If so, would you like to stay on as an owner
with push rights? (Would be great)

**Comment by GraemeBradbury** [comment]
My apologies, I could've sworn I replied.

I'm more than happy to continue being owner.

As it currently stands I need to cope with chars needing escape and give the package proper icons and it'll meet the requirements for a beta release.

I've added you as collaborator (I'm hoping that's enough privileges for the move)

**Comment by adamralph** [comment]
Thanks @GraemeBradbury. Unfortuately it seems that's not enough for me to able to transfer ownership of the repo. I guess I'll just create a repo under xbehave org and then we can just push everything there. Regarding the name of the repo - I was thinking that eventually the VS add in could do more than just paste from Gherkin. How about we give it a more general name: 'xbehave.net-visual-studio'?

**Comment by adamralph** [comment]
@GraemeBradbury to get things rolling, I've created the new repo and added you to the owners group with admin rights https://github.com/xbehave/xbehave.net-visual-studio

If you have an opinion on the repo name, we can still change it.

**Comment by GraemeBradbury** [comment]
@adamralph the name looks fine.
I have pushed the code into the new repo.
Will spend a bit of time getting the issues list updated a bit.

**Comment by adamralph** [comment]
@GraemeBradbury excellent. I guess we can just move this issue over to that repo now too.

**Comment by adamralph** [comment]
Issue moved to https://github.com/xbehave/xbehave.net-visual-studio/issues/3
