### ISSUE TITLE
Teardowns are not being called

### ISSUE THREAD

**Issue by anishpateluk** [xbehave/xbehave.net#50]
Teardown actions are not being invoked when writing tests

**Comment by adamralph** [comment]
Thanks for raising this issue. Can you please provide some code which demonstrates the problem?  As far as I know the teardown feature is working as expected.  I'm currently using it for a number of projects. Also, which version of xBehave.net are you using?

**Comment by anishpateluk** [comment]
I apologise for opening this issue. After trying to recreate the issue I have found that this was a problem with my test runner and not xBehave.

**Comment by adamralph** [comment]
OK, no problem! I'm glad xBehave.net is working well for you.
