### ISSUE TITLE
Add optional continuation on failure after the execution of specific step types

### ISSUE THREAD

**Issue by adamralph** [xbehave/xbehave.net#57]
Currently xBehave exhibits 'fail-fast' behaviour. That is, when a step fails, all following steps are automatically failed. The proposal is to allow the scenario author to control this behaviour, e.g. if a Then step has already run in the current scenario, continue running all subsequent steps.

From the discussion at https://github.com/xbehave/xbehave.net/pull/56:

We could have an attribute that can be applied at either the assembly, class or method level which controls the type of step after which fail fast should NOT occur. The levels could be controlled by enum values:

None (default if missing)
Given
When
Then
And
But
All
The most commonly used would definitely be None, Then and perhaps All but the others should be present for completeness to cover edge cases.

The next problem is how to match the enum values to the steps. The SDK would have to expose a way for the public API to tell it which step has been called. Whilst this is simple for the default GWT DSL, we have to take into account someone writing a custom DSL. Although the SDK is internal at the moment, the plan has always been to expose it publicly in version 1.0 or soon after. This means someone can potentially dispose with the default DSL completely and create their own.

I think a general solution which would work for both the default DSL and a custom DSL is to add an overload of CurrentScenario.AddStep() which accepts an extra step type parameter as object and also add an overload of the attribute constructor which also accepts an object. During scenario execution, if the attribute setting for current scenario resolves to All or None then the step type of the current step is ignored and fail fast is determined purely by the attribute setting. If the attribute setting resolves to something else, the step type is compared for equality to the attribute setting and fail fast is only disabled if they match.

**Comment by adamralph** [comment]
merged contribution from @jamesfoster https://github.com/xbehave/xbehave.net/commit/3091c71efa065986571957530287ecb8bd6ec8c6

**Comment by adamralph** [comment]
@jamesfoster I've pushed out a beta package, can you please give it a try https://nuget.org/packages/Xbehave/0.15.0-beta01

**Comment by jamesfoster** [comment]
Been using it for the last few days and I've had no problems. It's nice to see those little red X's next to all failing steps instead of just the first one.

I've just put `[assembly: ContinueOnFailureAfter(StepType.Then)]` in the AssemblyInfo file.

Bonza!

**Comment by adamralph** [comment]
Good to hear! :smile:
